name: fishbowl-train
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - pip
  - pip:
      - ultralytics
      - opencv-python
      - numpy
      - pyyaml
      - tqdm
      - matplotlib
      - jupyter
